### ISSUE TITLE
New delivery; add package set selection, weight selection (Dropoff) [API changes required]

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-app#1790]
#### 2nd page current design
![6CFB79F6-2D59-446C-9D0F-A3D7139FC3E5_1_102_o](https://github.com/coopcycle/coopcycle-app/assets/77277854/a408936d-71a0-4049-abf2-32aed96f6f6b)

It contains:

1. uneditable address field
2. phone number field
3. person to contact field
4. delivery info comment box
5. day and time range picker OR dropdown menu of preconfigured time slots with text descriptions

It does not have Packages, time slot selection, weight, or tags.

#### Things to change

- [x] take away address field; todo in https://github.com/coopcycle/coopcycle-app/issues/1789
- [x] move phone nuimber to 1st page; todo in https://github.com/coopcycle/coopcycle-app/issues/1789
- [x] move person to contact field to 1st page; todo in https://github.com/coopcycle/coopcycle-app/issues/1789
- [ ] add package selection feature
- [x] add weight field (obligatory or not based on store configuration)
~~- [ ] add tags field; ❗️currently: task tags are used; are they for internal use only? + no API to list and set them~~
- [x] fix: send comments to the API (does not seem happening at the moment)
- [x] Add time slot selection feature; automatically is default time slot; todo in https://github.com/coopcycle/coopcycle-app/issues/1791
- [x] Add time range selector; automatically prefill next possible time range; todo in https://github.com/coopcycle/coopcycle-app/issues/1791

#### 2nd page dirty design
![image](https://github.com/coopcycle/coopcycle-app/assets/77277854/e5b5c2a7-bc03-4283-8aca-db820b248b95)

#### 2nd page final design
TO DO

#### Implementation

- [ ] add: return store configuration in `/api/me/stores` endpoint

#### Additional info

`POST {{host}}/api/deliveries`

```
{
  "store": "/api/stores/1",
  "dropoff": {
    "address": "/api/addresses/53",
    "before": "2024-05-24T17:28:47-07:00",
    "packages": [
      {"type": "Boxes", "quantity": 2}
    ],
    "weight": 1500,
    "comments": "Please call me before delivery"
  }
}
```

or use a different endpoint: https://github.com/coopcycle/coopcycle-web/issues/4335
